"use strict";
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],KEY="jobbuddy.interviewDesk.v1",STAGES=["准备投递","已投递","笔试","一面","二面","HR 面","Offer","结束"];
const seed={jobs:[],jd:{},profile:{},resumeRaw:"",recaps:[],recapFolders:["全部","秋招","实习"],stars:0,mode:false,activeJobId:null,weekly:"",boundaries:"",agentMemory:[],ocrDocuments:[],prepEdits:{},settings:{theme:"light",displayName:"伙伴",recapSeeded:false,recapPaneWidths:{folders:240,answers:260}}};
const projects=[
 {id:"project-launch",cat:"产品营销",title:"新品上市项目",keys:["用户分层","信息架构","跨团队协作","阶段复盘"],detail:"讲清背景、你的判断、关键取舍、执行动作和可验证结果。"},
 {id:"project-community",cat:"增长运营",title:"社区增长 0→1",keys:["目标用户","小样本验证","内容机制","反馈闭环"],detail:"用用户洞察、验证过程和迭代结果解释渠道价值。"},
 {id:"project-content",cat:"内容增长",title:"内容增长项目",keys:["真实场景","痛点解决","内容组合","转化漏斗"],detail:"说明内容策略如何从用户问题出发，并通过数据持续优化。"},
 {id:"project-ai",cat:"AI 项目",title:"AI 工作流原型",keys:["业务痛点","PRD / MVP","模型调用","人工复核"],detail:"用真实调用和验证结果证明不是静态 Demo，并说明人机分工边界。"}
];
const questions=[
 {id:"q-project-hard",cat:"项目深挖",title:"项目最困难的地方？",keys:["约束变化","优先级","资源取舍","核心链路"],detail:"难点不是赶工，而是在不确定中做资源取舍。"},
 {id:"q-product",cat:"岗位题",title:"为什么转向产品？",keys:["不是逃离市场","问题抽象","完整闭环","已开始行动"],detail:"从业务痛点走向需求、规则、原型和验证。"},
 {id:"q-channel",cat:"项目深挖",title:"为什么选择这个渠道？",keys:["用户匹配","直接反馈","内容沉淀","小样本验证"],detail:"回答渠道与目标用户、验证成本和长期价值的关系。"},
 {id:"q-mvp",cat:"岗位题",title:"如何定义 MVP？",keys:["最高频痛点","最短验证链","成功指标","暂不做"],detail:"用 Copy QA 的准确性、品牌表达和人工通过率回答。"},
 {id:"q-credit",cat:"压力题",title:"哪些结果由你负责？",keys:["直接负责","推动","参与","团队结果"],detail:"主动划清个人动作与项目结果。"},
 {id:"q-ai",cat:"行业题",title:"AI 产品如何做人机分工？",keys:["模型规模化","规则边界","人工审批","反馈闭环"],detail:"人负责高风险判断、品牌责任与例外。"}
];
const cases=[
 {id:"case-content",cat:"个人内容",title:"代表内容案例",keys:["开头钩子","情绪转折","评论反馈"],detail:"补成四句话：写给谁；前三秒如何停住用户；中段如何推进；用哪个数据或评论证明有效。"},
 {id:"case-hot",cat:"热点内容",title:"热点内容观察模板",keys:["为什么此刻","谁在传播","可复用结构","品牌边界"],detail:"记录热点起因、核心情绪、平台机制、结构和衰减周期；回答品牌为什么应该跟或不应该跟。"},
 {id:"case-competitor",cat:"竞品案例",title:"竞品上市内容拆解",keys:["声量趋势","渠道结构","品牌词承接","内容节奏"],detail:"以声量、搜索、投放节奏和用户口碑四个维度形成可复用的竞品观察。"}
];
const intros=[
 {id:"intro-zh30",cat:"自我介绍",title:"中文 30 秒",keys:["当前身份","核心方向","代表经历","岗位连接"],detail:"面试官您好，我是［姓名］。我目前专注于［方向］，曾通过［代表项目］解决［核心问题］并取得［结果］。我希望把这段能力带到［目标岗位］，继续解决［岗位关键问题］。"},
 {id:"intro-zh60",cat:"自我介绍",title:"中文 1 分钟",keys:["身份定位","两项能力","项目证据","求职动机"],detail:"用两条互补能力串联 2–3 个项目证据，最后落到为什么选择当前公司和岗位。"},
 {id:"intro-en30",cat:"自我介绍",title:"English 30s",keys:["current focus","core strength","proof point","role fit"],detail:"Hi, I’m [Name]. I focus on [area] and have worked on [project], where I [action] and achieved [result]. I’m excited to bring this experience to [role] and help solve [key challenge]."}
];
const NAV=[["home","⌂","首页"],["jd","⌁","JD 与匹配"],["profile","◉","简历档案"],["prep","◇","准备库"],["recap","↻","面试复盘"]];
let data,prepType="面试故事库",prepCategory="全部",prepTag="全部",prepShowAllTags=false,detailTagsDraft=[],timerTotal=45,timerLeft=45,timerId=null,homeTransitionTimer=null,currentRecap=0,currentAnswer=0,currentFolder="全部",editingJob=null,detailSource=null;
async function readData(){let incoming={};if(globalThis.chrome?.storage?.local){const r=await chrome.storage.local.get(KEY);incoming=r[KEY]||{}}else{try{incoming=JSON.parse(localStorage.getItem(KEY)||"{}")||{}}catch{}}return migrate(Object.assign(structuredClone(seed),incoming))}
function migrate(next){next.recapFolders=Array.isArray(next.recapFolders)&&next.recapFolders.length?next.recapFolders:["全部","秋招","实习"];next.prepEdits=next.prepEdits||{};next.settings=Object.assign({theme:"light",displayName:"伙伴",recapSeeded:false,recapPaneWidths:{folders:240,answers:260}},next.settings||{});next.settings.recapPaneWidths=Object.assign({folders:240,answers:260},next.settings.recapPaneWidths||{});next.jobs=(next.jobs||[]).map(j=>Object.assign({},j,{readiness:j.readiness||(+j.progress>=100?"已准备":+j.progress>0?"准备中":"未开始"),updatedAt:j.updatedAt||j.date||j.createdAt||new Date().toISOString()}));next.recaps=(next.recaps||[]).map(r=>{if(Array.isArray(r.answers))return r;return{id:r.id||crypto.randomUUID(),role:r.role||"历史复盘",date:r.date||"",folder:r.folder||"秋招",answers:[{id:crypto.randomUUID(),question:r.question||"",original:r.original||"",problem:r.problem||"",improved:r.improved||""}]}});return next}
async function writeData(){if(globalThis.chrome?.storage?.local)await chrome.storage.local.set({[KEY]:data});else localStorage.setItem(KEY,JSON.stringify(data))}
function esc(s=""){return String(s).replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]))}
function toast(s){$("#toast").textContent=s;$("#toast").classList.add("show");clearTimeout(toast.t);toast.t=setTimeout(()=>$("#toast").classList.remove("show"),2600)}
function show(id){$$('.view').forEach(x=>x.classList.toggle('active',x.id===id));$$('[data-view]').forEach(x=>x.classList.toggle('active',x.dataset.view===id));window.scrollTo(0,0);const h=$("#"+id+" h1");if(h){h.tabIndex=-1;h.focus({preventScroll:true})}}
function renderNav(){$("#nav").innerHTML=NAV.map(x=>`<button data-view="${x[0]}" class="${x[0]==="home"?"active":""}"><i>${x[1]}</i>${x[2]}</button>`).join("");$$('[data-view]').forEach(b=>b.onclick=()=>show(b.dataset.view))}
function renderIdentity(){const name=data.settings.displayName?.trim()||"伙伴";$("#brandUser").textContent=name;$("#displayName").value=name;document.title="求职buddy · "+name;renderDate()}
function renderDate(){const d=new Date(),h=d.getHours(),name=data?.settings?.displayName?.trim()||"伙伴",g=(h<11?"早上":h<18?"下午":"晚上")+"好，"+name;$("#greeting").textContent=g;$("#gateGreeting").textContent=g;$("#day").textContent=String(d.getDate()).padStart(2,"0");$("#dateText").textContent=new Intl.DateTimeFormat("zh-CN",{month:"long",weekday:"long"}).format(d)}
function stageClass(s){return s==="Offer"?"green":s.includes("面")?"blue":"amber"}
function readinessClass(s){return s==="已准备"?"green":s==="准备中"?"amber":""}
function formatUpdatedAt(value){if(!value)return"尚未记录";const d=new Date(value);return Number.isNaN(d.getTime())?"尚未记录":d.toLocaleString("zh-CN",{month:"numeric",day:"numeric",hour:"2-digit",minute:"2-digit"})}
function renderHome(){const live=data.jobs.filter(x=>!["Offer","结束"].includes(x.stage)),ready=data.jobs.filter(x=>x.readiness==="已准备").length;$("#stats").innerHTML=[[live.length,"进行中的岗位"],[ready+"/"+data.jobs.length,"已准备岗位"],[data.stars||0,"完成 STAR 练习"],[data.recaps.length,"面试复盘"]].map(x=>`<div class="stat"><b>${x[0]}</b><span>${x[1]}</span></div>`).join("");const fs=["准备投递","已投递","笔试","一面","二面","Offer"];$("#funnel").innerHTML=fs.map(s=>`<div><b>${data.jobs.filter(x=>x.stage===s).length}</b>${s}</div>`).join("");$("#jobRows").innerHTML=data.jobs.length?data.jobs.map((j,i)=>`<tr><td><b>${esc(j.company)}</b><br><span class="muted">${esc(j.role)}</span></td><td><span class="pill ${stageClass(j.stage)}">${esc(j.stage)}</span></td><td><span class="updated-at">${esc(formatUpdatedAt(j.updatedAt))}</span></td><td><span class="pill ${readinessClass(j.readiness)}">${esc(j.readiness||"未开始")}</span></td><td><button class="secondary small" data-advance="${i}" ${["Offer","结束"].includes(j.stage)?"disabled":""}>推进</button></td><td><button class="ghost small" data-edit="${i}">编辑</button><button class="ghost small" data-delete="${i}">删除</button></td></tr>`).join(""):'<tr><td class="empty" colspan="6">还没有岗位。添加第一个目标后，就能查看状态和准备情况。</td></tr>';$$('[data-advance]').forEach(b=>b.onclick=()=>advance(+b.dataset.advance));$$('[data-edit]').forEach(b=>b.onclick=()=>openJob(+b.dataset.edit));$$('[data-delete]').forEach(b=>b.onclick=()=>removeJob(+b.dataset.delete));$("#weekly").value=data.weekly||$("#weekly").value;$("#boundaries").value=data.boundaries||$("#boundaries").value;$("#gateFocus").textContent=data.weekly?.split("\n").find(Boolean)?.replace(/^\d+[.、]\s*/,"")||"点击进入今日工作台"}
function unlockHome(open=true,withMotion=false){clearTimeout(homeTransitionTimer);const home=$("#home"),gate=$("#focusGate"),companion=$("#focusCompanion"),dashboard=$("#homeDashboard"),reduced=matchMedia("(prefers-reduced-motion: reduce)").matches;home.classList.remove("is-unlocking");dashboard.classList.remove("is-entering");gate.disabled=false;if(!open){gate.hidden=false;gate.style.display="";companion.hidden=false;dashboard.classList.add("is-locked");dashboard.setAttribute("aria-hidden","true");sessionStorage.removeItem("chris-home-open");return}sessionStorage.setItem("chris-home-open","1");if(withMotion&&!reduced){home.classList.add("is-unlocking");gate.disabled=true;homeTransitionTimer=setTimeout(()=>{gate.hidden=true;gate.style.display="none";companion.hidden=true;dashboard.classList.remove("is-locked");dashboard.classList.add("is-entering");dashboard.setAttribute("aria-hidden","false");home.classList.remove("is-unlocking");gate.disabled=false;homeTransitionTimer=setTimeout(()=>dashboard.classList.remove("is-entering"),620)},440);return}gate.hidden=true;gate.style.display="none";companion.hidden=true;dashboard.classList.remove("is-locked");dashboard.setAttribute("aria-hidden","false")}
function openJob(i=null){editingJob=i;const j=i===null?{company:"",role:"",stage:"准备投递",readiness:"未开始",updatedAt:new Date().toISOString()}:data.jobs[i];$("#jCompany").value=j.company||"";$("#jRole").value=j.role||"";$("#jStage").value=j.stage||"准备投递";$("#jReadiness").value=j.readiness||"未开始";$("#jUpdatedAt").value=formatUpdatedAt(j.updatedAt);$("#jobDialog").showModal()}
async function saveJob(e){e.preventDefault();const previous=editingJob===null?null:data.jobs[editingJob],now=new Date().toISOString(),stage=$("#jStage").value,j={...(previous||{}),id:previous?.id||crypto.randomUUID(),company:$("#jCompany").value,role:$("#jRole").value,stage,readiness:$("#jReadiness").value,updatedAt:!previous||previous.stage!==stage?now:previous.updatedAt||now,createdAt:previous?.createdAt||now};if(editingJob===null)data.jobs.unshift(j);else data.jobs[editingJob]=j;data.activeJobId=j.id;await writeData();$("#jobDialog").close();renderHome();toast(previous?.stage!==stage?"岗位状态已更新":"岗位已保存")}
async function advance(i){const n=STAGES.indexOf(data.jobs[i].stage);if(n>=0&&n<STAGES.length-2){data.jobs[i].stage=STAGES[n+1];data.jobs[i].updatedAt=new Date().toISOString()}await writeData();renderHome();toast("已推进至 "+data.jobs[i].stage)}
async function removeJob(i){if(!confirm(`删除 ${data.jobs[i].company} / ${data.jobs[i].role}？`))return;data.jobs.splice(i,1);await writeData();renderHome()}
function loadJd(){["Company","Role","Raw","Duties","Requirements","Matches","Risks"].forEach(k=>$("#jd"+k).value=data.jd[k.toLowerCase()]||"")}
async function saveJd(){data.jd={};["Company","Role","Raw","Duties","Requirements","Matches","Risks"].forEach(k=>data.jd[k.toLowerCase()]=$("#jd"+k).value);await writeData();toast("JD 拆解已保存")}
function edited(x,type){const key=type+":"+x.id,o=data.prepEdits[key]||{};return Object.assign({},x,o,{_key:key,_type:type})}
function card(x,type,label){x=edited(x,type);return `<article class="card prep-card" tabindex="0" role="button" data-detail-key="${esc(x._key)}"><span class="pill">${esc(label||x.cat||"自我介绍")}</span><span class="card-action" aria-hidden="true">详情</span><h3>${esc(x.title)}</h3><div class="tags">${(x.keys||[]).map(k=>`<span class="tag">${esc(k)}</span>`).join("")}</div><p class="detail">${esc(x.detail)}</p></article>`}
function storyCard(s){const key="story:"+s.id,o=data.prepEdits[key]||{},x=Object.assign({},s,o),answer=x.detail||x.answer||x.support||x.oneLiner||"暂无完整版本";return `<article class="card prep-card story-card" tabindex="0" role="button" id="story-${esc(s.id)}" data-detail-key="${esc(key)}"><div><span class="story-id">${esc(s.id)}</span><span class="pill grade">对外 ${esc(s.grade||"待确认")}</span></div><span class="card-action" aria-hidden="true">详情</span><h3>${esc(x.title)}</h3><div class="tags">${(x.keys||x.tags||[]).map(k=>`<span class="tag">#${esc(k)}</span>`).join("")}</div><p class="detail">${esc(answer)}</p></article>`}
function renderStoryLibrary(){const lib=globalThis.StoryLibrary;if(!lib?.stories?.length)return `<div class="empty">${esc(lib?.error||"正在读取面试故事库…")}</div>`;const cats=["全部",...new Set(lib.stories.map(x=>x.category))];return `<div class="story-summary"><div><b>${lib.stories.length} 个完整案例</b><span>点击卡片查看、修改完整答案与表达边界</span></div></div><div class="filters">${cats.map((c,i)=>`<button data-story-cat="${esc(c)}" class="${i===0?"active":""}">${esc(c)}</button>`).join("")}</div><div class="cards story-cards">${lib.stories.map(storyCard).join("")}</div>`}
function bindPrepCards(){$$('[data-detail-key]').forEach(el=>{el.onclick=()=>openDetail(el.dataset.detailKey);el.onkeydown=e=>{if(e.key==="Enter"||e.key===" "){e.preventDefault();openDetail(el.dataset.detailKey)}}})}
function renderPrep(){const types=["面试故事库","项目库","问题库","内容案例","自我介绍"];$("#prepTabs").innerHTML=types.map(t=>`<button data-prep="${t}" class="${t===prepType?"active":""}" aria-pressed="${t===prepType}">${t}</button>`).join("");$$('[data-prep]').forEach(b=>b.onclick=()=>{prepType=b.dataset.prep;prepCategory=prepTag="全部";prepShowAllTags=false;renderPrep()});let list,type,isStory=false;if(prepType==="面试故事库"){list=globalThis.StoryLibrary?.stories||[];type="story";isStory=true;if(!list.length){$("#prepContent").innerHTML=`<div class="empty">${esc(globalThis.StoryLibrary?.error||"正在读取面试故事库…")}</div>`;return}}else [list,type]={"项目库":[projects,"project"],"问题库":[questions,"question"],"内容案例":[cases,"case"],"自我介绍":[intros,"intro"]}[prepType];const enriched=list.map(x=>{const o=data.prepEdits[type+":"+x.id]||{};return{base:x,cat:x.category||x.cat||"未分类",keys:o.keys||x.tags||x.keys||[]}}),cats=["全部",...new Set(enriched.map(x=>x.cat))],tags=["全部",...new Set(enriched.flatMap(x=>x.keys))];if(!cats.includes(prepCategory))prepCategory="全部";if(!tags.includes(prepTag))prepTag="全部";let shownTags=prepShowAllTags?tags:tags.slice(0,13);if(prepTag!=="全部"&&!shownTags.includes(prepTag))shownTags.push(prepTag);const visible=enriched.filter(x=>(prepCategory==="全部"||x.cat===prepCategory)&&(prepTag==="全部"||x.keys.includes(prepTag)));$("#prepContent").innerHTML=`${isStory?`<div class="story-summary"><div><b>${list.length} 个完整案例</b><span>所有标签都可自定义，并直接用于筛选</span></div></div>`:""}<div class="filter-stack"><div class="filter-row"><span>分类</span><div class="filters">${cats.map(c=>`<button data-prep-cat="${esc(c)}" class="${c===prepCategory?"active":""}" aria-pressed="${c===prepCategory}">${esc(c)}</button>`).join("")}</div></div><div class="filter-row"><span>标签</span><div class="filters tag-filters">${shownTags.map(t=>`<button data-prep-tag="${esc(t)}" class="${t===prepTag?"active":""}" aria-pressed="${t===prepTag}">${t==="全部"?"全部标签":"# "+esc(t)}</button>`).join("")}${tags.length>13?`<button class="more-tags" data-toggle-tags>${prepShowAllTags?"收起标签":"更多标签 · "+(tags.length-13)}</button>`:""}</div></div></div><div class="cards ${isStory?"story-cards":""}">${visible.length?visible.map(x=>isStory?storyCard(x.base):card(x.base,type)).join(""):'<div class="empty wide">没有符合当前筛选的内容</div>'}</div>`;$$('[data-prep-cat]').forEach(b=>b.onclick=()=>{prepCategory=b.dataset.prepCat;renderPrep()});$$('[data-prep-tag]').forEach(b=>b.onclick=()=>{prepTag=b.dataset.prepTag;renderPrep()});$("[data-toggle-tags]")?.addEventListener("click",()=>{prepShowAllTags=!prepShowAllTags;renderPrep()});bindPrepCards()}
function findDetail(key){const [type,id]=key.split(":");if(type==="story"){const s=globalThis.StoryLibrary?.stories.find(x=>x.id===id);return s?{base:s,title:s.title,keys:s.tags,detail:s.answer||s.support||s.oneLiner,boundaries:s.boundaries||"",type:"面试故事"}:null}const all={project:projects,question:questions,case:cases,intro:intros}[type],x=all?.find(x=>x.id===id);return x?{base:x,title:x.title,keys:x.keys,detail:x.detail,boundaries:"",type:x.cat||type}:null}
function renderDetailTags(){$("#detailTags").value=detailTagsDraft.join("，");$("#detailTagChips").innerHTML=detailTagsDraft.length?detailTagsDraft.map((tag,i)=>`<button type="button" data-remove-detail-tag="${i}" aria-label="删除标签 ${esc(tag)}"><span>${esc(tag)}</span>×</button>`).join(""):'<span class="tag-empty">还没有标签</span>';$$('[data-remove-detail-tag]').forEach(b=>b.onclick=()=>{detailTagsDraft.splice(+b.dataset.removeDetailTag,1);renderDetailTags()})}
function addDetailTag(){const values=$("#detailTagInput").value.split(/[，,]/).map(x=>x.trim()).filter(Boolean);for(const value of values)if(!detailTagsDraft.includes(value))detailTagsDraft.push(value);$("#detailTagInput").value="";renderDetailTags();$("#detailTagInput").focus()}
function openDetail(key){const x=findDetail(key);if(!x)return;const o=data.prepEdits[key]||{};detailSource=x;detailTagsDraft=[...(o.keys||x.keys||[])];$("#detailKey").value=key;$("#detailType").textContent=x.type;$("#detailTitle").value=o.title||x.title;$("#detailTitleHeading").textContent=o.title||x.title;renderDetailTags();$("#detailBody").value=o.detail||x.detail||"";$("#detailBoundary").value=o.boundaries||x.boundaries||"";$("#detailBoundaryField").hidden=!key.startsWith("story:");$("#detailDialog").showModal()}
async function saveDetail(e){e.preventDefault();if($("#detailTagInput").value.trim())addDetailTag();const key=$("#detailKey").value;data.prepEdits[key]={title:$("#detailTitle").value.trim(),keys:[...detailTagsDraft],detail:$("#detailBody").value.trim(),boundaries:$("#detailBoundary").value.trim()};await writeData();$("#detailDialog").close();renderPrep();toast("内容与标签已保存")}
function normalizeRecaps(){if(!data.recaps.length&&!data.settings.recapSeeded){data.recaps.push({id:crypto.randomUUID(),role:"第一次复盘示例",date:"",folder:"秋招",answers:[{id:crypto.randomUUID(),question:"请用一个项目说明你如何处理变化。",original:"我介绍了项目背景和做过的许多工作，但没有说清取舍标准。",problem:"背景太长；动作没有优先级；团队结果听起来像个人归因。",improved:"先说明双重变更与核心判断，再用必须、延后、取消三档讲动作，最后区分个人负责与项目结果。"}]});data.settings.recapSeeded=true}}
function currentRecapObj(){return data.recaps[currentRecap]||data.recaps[0]}
function applyRecapPaneWidths(){const workspace=$(".recap-workspace"),w=data.settings.recapPaneWidths;workspace.style.setProperty("--folders-w",w.folders+"px");workspace.style.setProperty("--answers-w",w.answers+"px");$$('[data-resize-pane]').forEach(s=>s.setAttribute("aria-valuenow",String(w[s.dataset.resizePane]))) }
function resizeRecapPane(type,value,save=false){const limits=type==="folders"?[190,420]:[210,480];data.settings.recapPaneWidths[type]=Math.min(limits[1],Math.max(limits[0],Math.round(value)));applyRecapPaneWidths();if(save)writeData()}
function setupRecapResizers(){applyRecapPaneWidths();$$('[data-resize-pane]').forEach(separator=>{separator.onpointerdown=e=>{if(innerWidth<=900)return;e.preventDefault();const type=separator.dataset.resizePane,startX=e.clientX,start=data.settings.recapPaneWidths[type];document.body.classList.add("is-resizing");const move=event=>resizeRecapPane(type,start+event.clientX-startX);const up=()=>{document.removeEventListener("pointermove",move);document.removeEventListener("pointerup",up);document.body.classList.remove("is-resizing");writeData()};document.addEventListener("pointermove",move);document.addEventListener("pointerup",up,{once:true})};separator.onkeydown=e=>{if(!["ArrowLeft","ArrowRight","Home"].includes(e.key))return;e.preventDefault();const type=separator.dataset.resizePane;if(e.key==="Home")resizeRecapPane(type,type==="folders"?240:260,true);else resizeRecapPane(type,data.settings.recapPaneWidths[type]+(e.key==="ArrowRight"?16:-16),true)};separator.ondblclick=()=>resizeRecapPane(separator.dataset.resizePane,separator.dataset.resizePane==="folders"?240:260,true)})}
function renderRecaps(){normalizeRecaps();let visible=data.recaps.map((r,i)=>({r,i})).filter(x=>currentFolder==="全部"||x.r.folder===currentFolder);if(visible.length&&!visible.some(x=>x.i===currentRecap))currentRecap=visible[0].i;$("#folderList").innerHTML=data.recapFolders.map(f=>`<button data-folder="${esc(f)}" class="${f===currentFolder?"active":""}">${esc(f)} <span>${f==="全部"?data.recaps.length:data.recaps.filter(r=>r.folder===f).length}</span></button>`).join("");$("#recapList").innerHTML=visible.map(({r,i})=>`<button data-recap="${i}" class="${i===currentRecap?"active":""}">${esc(r.role||"未命名")}<span>${esc(r.date||"日期未填")}</span></button>`).join("")||'<div class="empty">这个文件夹还没有复盘<br><small>新建一场面试，我们从第一题开始。</small></div>';$$('[data-folder]').forEach(b=>b.onclick=()=>{currentFolder=b.dataset.folder;currentAnswer=0;renderRecaps()});$$('[data-recap]').forEach(b=>b.onclick=()=>{currentRecap=+b.dataset.recap;currentAnswer=0;renderRecaps()});const hasRecap=visible.length>0,r=hasRecap?currentRecapObj():null;$("#deleteFolder").disabled=["全部","秋招","实习"].includes(currentFolder);$("#deleteRecap").disabled=!hasRecap;$("#newAnswer").disabled=!hasRecap;$("#deleteAnswer").disabled=!hasRecap;$("#saveRecap").disabled=!hasRecap;["rRole","rDate","rQuestion","rOriginal","rProblem","rImproved"].forEach(id=>$("#"+id).disabled=!hasRecap);if(!hasRecap){$("#answerList").innerHTML='<div class="empty">暂无回答</div>';["rRole","rDate","rQuestion","rOriginal","rProblem","rImproved"].forEach(id=>$("#"+id).value="");return}r.answers=r.answers?.length?r.answers:[{id:crypto.randomUUID(),question:"",original:"",problem:"",improved:""}];if(currentAnswer>=r.answers.length)currentAnswer=0;$("#answerList").innerHTML=r.answers.map((a,i)=>`<button data-answer="${i}" class="${i===currentAnswer?"active":""}">${i+1}. ${esc(a.question||"未命名问题")}</button>`).join("");$$('[data-answer]').forEach(b=>b.onclick=()=>{currentAnswer=+b.dataset.answer;renderRecaps()});const a=r.answers[currentAnswer];$("#rRole").value=r.role||"";$("#rDate").value=r.date||"";["Question","Original","Problem","Improved"].forEach(k=>$("#r"+k).value=a[k.toLowerCase()]||"")}
async function saveRecap(){const r=currentRecapObj(),a=r.answers[currentAnswer];r.role=$("#rRole").value.trim()||"未命名面试";r.date=$("#rDate").value;["Question","Original","Problem","Improved"].forEach(k=>a[k.toLowerCase()]=$("#r"+k).value);await writeData();renderRecaps();renderHome();toast("本题与面试档案已保存")}
async function addRecap(){data.recaps.unshift({id:crypto.randomUUID(),role:"新面试",date:new Date().toISOString().slice(0,10),folder:currentFolder==="全部"?"秋招":currentFolder,answers:[{id:crypto.randomUUID(),question:"",original:"",problem:"",improved:""}]});currentRecap=currentAnswer=0;await writeData();renderRecaps()}
async function addAnswer(){const r=currentRecapObj();r.answers.push({id:crypto.randomUUID(),question:"",original:"",problem:"",improved:""});currentAnswer=r.answers.length-1;await writeData();renderRecaps()}
async function addFolder(){const name=prompt("新文件夹名称");if(!name?.trim()||data.recapFolders.includes(name.trim()))return;data.recapFolders.push(name.trim());currentFolder=name.trim();await writeData();renderRecaps()}
async function deleteAnswer(){const r=currentRecapObj(),a=r?.answers?.[currentAnswer];if(!a||!confirm(`删除第 ${currentAnswer+1} 条回答“${a.question||"未命名问题"}”？`))return;if(r.answers.length===1)r.answers=[{id:crypto.randomUUID(),question:"",original:"",problem:"",improved:""}];else r.answers.splice(currentAnswer,1);currentAnswer=Math.max(0,currentAnswer-1);await writeData();renderRecaps();toast(r.answers.length===1&&!r.answers[0].question?"已清空唯一回答":"回答已删除")}
async function deleteRecap(){const r=currentRecapObj();if(!r||!confirm(`删除整场面试复盘“${r.role||"未命名面试"}”？此操作无法撤销。`))return;data.recaps.splice(currentRecap,1);data.settings.recapSeeded=true;currentRecap=Math.max(0,currentRecap-1);currentAnswer=0;await writeData();renderRecaps();renderHome();toast("面试复盘已删除")}
async function deleteFolder(){if(["全部","秋招","实习"].includes(currentFolder))return;const name=currentFolder;if(!confirm(`删除文件夹“${name}”？其中的复盘会移动到“秋招”。`))return;data.recaps.forEach(r=>{if(r.folder===name)r.folder="秋招"});data.recapFolders=data.recapFolders.filter(f=>f!==name);currentFolder="全部";await writeData();renderRecaps();toast("文件夹已删除，复盘已移至秋招")}
async function importRecapMd(file){const text=await file.text(),lines=text.split(/\r?\n/),title=(lines.find(x=>/^#\s+/.test(x))||`# ${file.name.replace(/\.md$/i,"")}`).replace(/^#+\s*/,""),sections=[];let current=null;for(const line of lines){if(/^##\s+/.test(line)){if(current)sections.push(current);current={id:crypto.randomUUID(),question:line.replace(/^##\s+/,""),original:"",problem:"",improved:""}}else if(current)current.original+=(current.original?"\n":"")+line}if(current)sections.push(current);data.recaps.unshift({id:crypto.randomUUID(),role:title,date:new Date().toISOString().slice(0,10),folder:currentFolder==="全部"?"导入归档":currentFolder,answers:sections.length?sections:[{id:crypto.randomUUID(),question:"导入内容",original:text,problem:"",improved:""}]});if(!data.recapFolders.includes("导入归档"))data.recapFolders.push("导入归档");currentRecap=currentAnswer=0;await writeData();renderRecaps();renderHome();toast("MD 已归档为一场面试复盘")}
function drawClock(){const t=String(Math.floor(timerLeft/60)).padStart(2,"0")+":"+String(timerLeft%60).padStart(2,"0");$("#clock").textContent=t;$("#timerFab span").textContent=t}
function renderTimer(){const modes=[["一句话",15],["45 秒",45],["90 秒",90],["3 分钟",180]];$("#timerModes").innerHTML=modes.map(x=>`<button data-seconds="${x[1]}" class="${x[1]===timerTotal?"active":""}">${x[0]}</button>`).join("");$$('[data-seconds]').forEach(b=>b.onclick=()=>{clearInterval(timerId);timerId=null;timerTotal=timerLeft=+b.dataset.seconds;$("#startTimer").textContent="开始";renderTimer();drawClock()});drawClock()}
function toggleTimer(){if(timerId){clearInterval(timerId);timerId=null;$("#startTimer").textContent="继续";return}$("#startTimer").textContent="暂停";timerId=setInterval(async()=>{timerLeft--;drawClock();if(timerLeft<=0){clearInterval(timerId);timerId=null;data.stars=(data.stars||0)+1;await writeData();renderHome();$("#startTimer").textContent="再来一次";toast("本轮练习完成")}},1000)}
function toggleTimerDock(open){const dock=$("#timerDock"),fab=$("#timerFab");dock.classList.toggle("open",open);dock.setAttribute("aria-hidden",String(!open));fab.classList.toggle("is-open",open);fab.setAttribute("aria-expanded",String(open));fab.setAttribute("aria-label",open?"关闭 STAR 计时器":"打开 STAR 计时器")}
function doSearch(){const q=$("#search").value.trim().toLowerCase();if(!q){$("#searchBox").classList.remove("show");return}const storyItems=(globalThis.StoryLibrary?.stories||[]).map(s=>{const o=data.prepEdits["story:"+s.id]||{};return{title:s.id+" · "+(o.title||s.title),keys:[...(o.keys||s.tags||[]),...(s.roles||[])],detail:o.detail||[s.oneLiner,s.answer,s.support,s.boundaries].join(" "),kind:"story",storyId:s.id}}),contentItems=[[projects,"project"],[questions,"question"],[cases,"case"],[intros,"intro"]].flatMap(([list,type])=>list.map(x=>edited(x,type))),all=[...storyItems,...contentItems,...data.jobs.map(x=>({title:x.company+" / "+x.role,keys:[x.stage],detail:"岗位记录"}))],rs=all.filter(x=>(x.title+" "+(x.keys||[]).join(" ")+" "+x.detail).toLowerCase().includes(q)).slice(0,15);$("#searchBox").innerHTML=rs.length?rs.map((x,i)=>`<button data-result="${i}"><b>${esc(x.title)}</b><br><span class="muted">${esc((x.keys||[]).slice(0,5).join(" · "))}</span></button>`).join(""):'<div class="empty">没有找到相关内容</div>';$("#searchBox").classList.add("show");$$('[data-result]').forEach(b=>b.onclick=()=>{const item=rs[+b.dataset.result];if(item?.kind==="story")prepType="面试故事库";show("prep");renderPrep();$("#searchBox").classList.remove("show");$("#search").value="";if(item?.storyId)setTimeout(()=>openDetail("story:"+item.storyId),0)})}
async function exportData(){const blob=new Blob([JSON.stringify({schema:2,exportedAt:new Date().toISOString(),data},null,2)],{type:"application/json"}),url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download="chris-career-desk-"+new Date().toISOString().slice(0,10)+".json";a.click();URL.revokeObjectURL(url);toast("备份已下载")}
async function importData(file){try{const parsed=JSON.parse(await file.text()),incoming=parsed.data||parsed;if(!incoming.jobs||!incoming.recaps)throw Error();data=migrate(Object.assign(structuredClone(seed),incoming));await writeData();renderAll();toast("备份已导入")}catch{toast("无法识别这个备份文件")}}
function setTheme(theme){document.documentElement.dataset.theme=theme;localStorage.setItem("chris-desk-theme",theme);data.settings.theme=theme;$$('[data-theme-choice]').forEach(b=>b.classList.toggle('active',b.dataset.themeChoice===theme));writeData()}
async function savePersonalization(){data.settings.displayName=$("#displayName").value.trim()||"伙伴";await writeData();renderIdentity();toast("称呼已更新，求职buddy记住了")}
function renderAll(){renderIdentity();renderHome();loadJd();renderPrep();renderRecaps();document.body.classList.toggle("interview",!!data.mode);$("#modeBtn").setAttribute("aria-pressed",!!data.mode);if(globalThis.DeskIntelligence){globalThis.DeskIntelligence.loadProfile();globalThis.DeskIntelligence.render()}setTheme(document.documentElement.dataset.theme||data.settings.theme||"light")}
async function init(){data=await readData();renderNav();renderTimer();renderAll();setupRecapResizers();unlockHome(sessionStorage.getItem("chris-home-open")==="1");$("#focusGate").onclick=()=>unlockHome(true,true);$("#focusAgent").onclick=()=>{show("jd");setTimeout(()=>$("#jdRaw").focus(),0)};$("#relockHome").onclick=()=>unlockHome(false);$("#newJob").onclick=()=>openJob();$("#jobForm").onsubmit=saveJob;$$('[data-close]').forEach(b=>b.onclick=()=>b.closest("dialog").close());$("#detailForm").onsubmit=saveDetail;$("#addDetailTag").onclick=addDetailTag;$("#detailTagInput").onkeydown=e=>{if(e.key==="Enter"){e.preventDefault();addDetailTag()}};$("#saveJd").onclick=saveJd;for(const id of ["weekly","boundaries"]){$("#"+id).oninput=()=>{clearTimeout($("#"+id)._t);$("#"+id)._t=setTimeout(async()=>{data[id]=$("#"+id).value;await writeData();renderHome()},350)}}$("#modeBtn").onclick=async()=>{data.mode=!data.mode;await writeData();renderAll();toast(data.mode?"面试模式：只显示关键词":"已返回准备模式")};$("#timerFab").addEventListener("click",e=>{e.preventDefault();e.stopPropagation();toggleTimerDock(!$("#timerDock").classList.contains("open"))});$("#closeTimer").onclick=()=>toggleTimerDock(false);$("#startTimer").onclick=toggleTimer;$("#resetTimer").onclick=()=>{clearInterval(timerId);timerId=null;timerLeft=timerTotal;$("#startTimer").textContent="开始";drawClock()};$("#newRecap").onclick=addRecap;$("#newAnswer").onclick=addAnswer;$("#newFolder").onclick=addFolder;$("#deleteAnswer").onclick=deleteAnswer;$("#deleteRecap").onclick=deleteRecap;$("#deleteFolder").onclick=deleteFolder;$("#saveRecap").onclick=saveRecap;$("#savePersonalization").onclick=savePersonalization;$("#displayName").onkeydown=e=>{if(e.key==="Enter")savePersonalization()};$("#importRecapMd").onclick=()=>$("#recapMdInput").click();$("#recapMdInput").onchange=e=>e.target.files[0]&&importRecapMd(e.target.files[0]);$("#search").oninput=doSearch;document.addEventListener("keydown",e=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==="k"){e.preventDefault();$("#search").focus()}if(e.key==="Escape"){$("#searchBox").classList.remove("show");toggleTimerDock(false)}});$("#backupBtn").onclick=()=>$("#backupDialog").showModal();$("#exportBtn").onclick=$("#backupExport").onclick=exportData;$("#importBtn").onclick=$("#backupImport").onclick=()=>$("#importInput").click();$("#importInput").onchange=e=>e.target.files[0]&&importData(e.target.files[0]);$$('[data-theme-choice]').forEach(b=>b.onclick=()=>setTheme(b.dataset.themeChoice))}
globalThis.DeskStore={get:()=>data,save:async next=>{data=next;await writeData();renderAll()},toast};globalThis.DeskStore.ready=init();if(globalThis.StoryLibrary)globalThis.StoryLibrary.ready.then(()=>data&&renderPrep());
globalThis.DeskStore.ready.then(()=>unlockHome(false));
