"use strict";
(()=>{
  const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],esc=s=>String(s||"").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));
  const labels={resume_fact:"简历事实",user_preference:"个人偏好",correction:"表达纠正",site_mapping:"字段映射",reference:"参考资料"};
  const fields={pName:"name",pEnglishName:"englishName",pEmail:"email",pPhone:"phone",pWebsite:"website",pLocation:"location",pRoles:"roles",pLocations:"locations",pGraduation:"graduation"};
  const defaults={name:"",englishName:"",roles:"",locations:"",graduation:""};
  const aiPresets={deepseek:{label:"DeepSeek",baseUrl:"https://api.deepseek.com",model:"deepseek-flash"},kimi:{label:"Kimi",baseUrl:"https://api.moonshot.cn/v1",model:"kimi-k2.5"}};
  let worker=null,pollTimer=null,lastUploadId="",aiSession={key:""};
  function state(){const d=globalThis.DeskStore.get();d.profile=d.profile||{};d.agentMemory=Array.isArray(d.agentMemory)?d.agentMemory:[];d.ocrDocuments=Array.isArray(d.ocrDocuments)?d.ocrDocuments:[];return d}
  function memory(content,type,source,verified=false){return{id:crypto.randomUUID(),content:content.trim(),type,source,confidence:verified?"high":"pending",verified,createdAt:new Date().toISOString()}}
  async function save(d,message){await globalThis.DeskStore.save(d);if(message)globalThis.DeskStore.toast(message)}
  function seedMemory(d){if(d.agentMemory.length)return false;d.agentMemory=[memory("表达项目成果时，区分个人动作与团队结果。","correction","示例记忆",true),memory("请在设置中填写你的求职地点偏好。","user_preference","示例记忆",false),memory("简历中的时间、数据和项目归因需要本人确认。","resume_fact","示例记忆",false)];return true}
  function loadProfile(){const d=state();Object.entries(fields).forEach(([id,key])=>$("#"+id).value=d.profile[key]??defaults[key]??"");$("#resumeRaw").value=d.resumeRaw||""}
  async function saveProfile(){const d=state();Object.entries(fields).forEach(([id,key])=>d.profile[key]=$("#"+id).value.trim());d.resumeRaw=$("#resumeRaw").value.trim();await save(d,"简历与职业档案已保存")}
  function renderLedger(){const list=state().agentMemory.slice().sort((a,b)=>String(b.createdAt).localeCompare(String(a.createdAt)));$("#memoryLedger").innerHTML=list.length?list.map(m=>`<article class="memory-row"><div><span class="pill">${esc(labels[m.type]||m.type)}</span><small>${esc(m.source||"手动添加")}</small></div><div><p>${esc(m.content)}</p><small>${m.verified?'<span class="confidence high">已确认，可供 Agent 使用</span>':'<span class="confidence mid">待确认，不进入正式事实</span>'}</small></div><div class="actions">${m.verified?"":`<button class="secondary small" data-confirm-memory="${m.id}">确认</button>`}<button class="ghost small" data-delete-memory="${m.id}">删除</button></div></article>`).join(""):'<div class="empty">还没有 Agent 记忆</div>'}
  function context(){const d=state(),verified=d.agentMemory.filter(m=>m.verified),block=(title,type)=>`## ${title}\n${verified.filter(m=>m.type===type).map(x=>`- ${x.content}`).join("\n")||"- 暂无已确认内容"}`,profile=Object.entries(d.profile).filter(([,v])=>v).map(([k,v])=>`- ${k}: ${v}`).join("\n");return `# Job Search Buddy · 本地策略上下文\n\n原则：只把已确认内容作为事实；OCR、AI 推断和材料冲突必须由本人确认。\n\n## 职业档案\n${profile||"- 尚未保存"}\n\n${block("已确认事实","resume_fact")}\n\n${block("求职偏好","user_preference")}\n\n${block("表达纠正","correction")}`}
  function render(){const d=state(),list=d.agentMemory,verified=list.filter(m=>m.verified).length,types=new Set(list.filter(m=>m.verified).map(m=>m.type)).size,profileFilled=Object.values(d.profile).filter(Boolean).length,score=Math.min(100,Math.round(verified*8+types*7+profileFilled*3));$("#agentScore").textContent=score+"%";$("#agentBar").style.width=score+"%";$("#agentSummary").textContent=list.length?`${verified} 条已确认，${list.length-verified} 条待确认。`:"先添加第一条事实或表达纠正。";$("#agentContext").textContent=context();renderLedger()}
  function mountAiSettings(){if($("#aiSettings"))return;const panel=document.createElement("div");panel.id="aiSettings";panel.className="panel ai-settings";panel.innerHTML='<div class="panel-head"><div><h2>AI 模型</h2><p class="muted">密钥默认只保留在本次 Chrome 会话；不会进入备份或 GitHub。</p></div><span id="aiStatus" class="pill">未配置</span></div><div class="grid"><div class="field"><label for="aiProvider">供应商</label><select id="aiProvider"><option value="deepseek">DeepSeek</option><option value="kimi">Kimi</option></select></div><div class="field"><label for="aiModel">模型</label><input id="aiModel"></div><div class="field wide"><label for="aiBaseUrl">API 地址</label><input id="aiBaseUrl" inputmode="url"></div><div class="field wide"><label for="aiKey">API Key</label><input id="aiKey" type="password" autocomplete="off" placeholder="只粘贴在这里，不要提交到仓库"></div></div><p class="field-note warning">点击 AI 分析时，当前 JD 或简历内容会发送给所选供应商；发送前会再次确认。</p><div class="source-actions"><button id="saveAiSettings" class="primary">保存本次会话</button><button id="testAiConnection" class="secondary">测试连接</button><button id="clearAiKey" class="ghost">清除密钥</button></div>';
    $("#settings").append(panel);$("#aiProvider").onchange=()=>{const p=aiPresets[$("#aiProvider").value];$("#aiBaseUrl").value=p.baseUrl;$("#aiModel").value=p.model};$("#saveAiSettings").onclick=saveAiSettings;$("#testAiConnection").onclick=testAiConnection;$("#clearAiKey").onclick=clearAiKey}
  async function sessionGet(){if(globalThis.chrome?.storage?.session)return (await chrome.storage.session.get("jobBuddyAiSession")).jobBuddyAiSession||{};try{return JSON.parse(sessionStorage.getItem("jobBuddyAiSession")||"{}")}catch{return {}}}
  async function sessionSet(value){if(globalThis.chrome?.storage?.session)return chrome.storage.session.set({jobBuddyAiSession:value});sessionStorage.setItem("jobBuddyAiSession",JSON.stringify(value))}
  function aiConfig(){const d=state(),provider=d.settings?.ai?.provider||"deepseek",preset=aiPresets[provider]||aiPresets.deepseek;return{provider,baseUrl:d.settings?.ai?.baseUrl||preset.baseUrl,model:d.settings?.ai?.model||preset.model,key:aiSession.key||""}}
  function renderAiSettings(){if(!$("#aiSettings"))return;const c=aiConfig();$("#aiProvider").value=c.provider;$("#aiBaseUrl").value=c.baseUrl;$("#aiModel").value=c.model;$("#aiKey").value=c.key;$("#aiStatus").textContent=c.key?"本次会话已配置":"未配置";$("#aiStatus").className="pill "+(c.key?"green":"")}
  async function saveAiSettings(){const d=state(),provider=$("#aiProvider").value,key=$("#aiKey").value.trim();d.settings=d.settings||{};d.settings.ai={provider,baseUrl:$("#aiBaseUrl").value.trim().replace(/\/$/,""),model:$("#aiModel").value.trim()};aiSession={key};await sessionSet(aiSession);await save(d,key?"AI 已为本次 Chrome 会话配置":"已保存模型设置，请填写 API Key");renderAiSettings()}
  async function clearAiKey(){aiSession={key:""};await sessionSet(aiSession);renderAiSettings();globalThis.DeskStore.toast("本次会话的 API Key 已清除")}
  async function aiRequest(messages){const c=aiConfig();if(!c.key)throw Error("请先到设置 → AI 模型填写 API Key");const response=await fetch(c.baseUrl+"/chat/completions",{method:"POST",headers:{"Content-Type":"application/json","Authorization":"Bearer "+c.key},body:JSON.stringify({model:c.model,messages,temperature:.2,stream:false})});const body=await response.json().catch(()=>({}));if(!response.ok)throw Error(body?.error?.message||`接口返回 ${response.status}`);return body?.choices?.[0]?.message?.content||""}
  function parseJsonAnswer(text){const match=String(text).match(/\{[\s\S]*\}/);if(!match)throw Error("模型没有返回可识别的结构化结果");return JSON.parse(match[0])}
  async function testAiConnection(){try{await saveAiSettings();globalThis.DeskStore.toast("正在测试 AI 连接…");await aiRequest([{role:"user",content:"只回复 OK"}]);globalThis.DeskStore.toast("AI 连接成功")}catch(e){globalThis.DeskStore.toast(e.message||"AI 连接失败")}}
  async function addMemory(){const content=$("#memoryContent").value.trim();if(!content)return globalThis.DeskStore.toast("请先写下要记住的内容");const d=state();d.agentMemory.push(memory(content,$("#memoryType").value,"手动添加",$("#memoryVerified").checked));$("#memoryContent").value="";$("#memoryVerified").checked=false;await save(d,"已保存到 Agent 记忆账本")}
  async function confirmMemory(id){const d=state(),item=d.agentMemory.find(m=>m.id===id);if(!item)return;item.verified=true;item.confidence="high";item.verifiedAt=new Date().toISOString();await save(d,"已确认，可供 Agent 使用")}
  async function deleteMemory(id){const d=state(),item=d.agentMemory.find(m=>m.id===id);if(!item||!confirm("删除这条 Agent 记忆？"))return;d.agentMemory=d.agentMemory.filter(m=>m.id!==id);await save(d,"记忆已删除")}
  function imageCanvas(file){return new Promise((resolve,reject)=>{const reader=new FileReader();reader.onerror=()=>reject(Error("读取图片失败"));reader.onload=e=>{const img=new Image();img.onerror=()=>reject(Error("无法解码图片"));img.onload=()=>{const max=2400,scale=Math.min(1,max/Math.max(img.naturalWidth,img.naturalHeight)),canvas=document.createElement("canvas");canvas.width=Math.round(img.naturalWidth*scale);canvas.height=Math.round(img.naturalHeight*scale);const ctx=canvas.getContext("2d",{willReadFrequently:true});ctx.fillStyle="#fff";ctx.fillRect(0,0,canvas.width,canvas.height);ctx.drawImage(img,0,0,canvas.width,canvas.height);resolve(canvas)};img.src=e.target.result};reader.readAsDataURL(file)})}
  async function recognize(file,target,progress){if(!file?.type.startsWith("image/"))return globalThis.DeskStore.toast("请选择图片文件");const wrap=$(progress),bar=wrap.querySelector("i"),label=wrap.querySelector("span");wrap.hidden=false;bar.style.width="2%";label.textContent="正在加载离线中文识别…";try{const root=globalThis.chrome?.runtime?.getURL?chrome.runtime.getURL("ocr/"):new URL("./ocr/",location.href).href,canvas=await imageCanvas(file);worker=await Tesseract.createWorker("chi_sim",1,{workerPath:root+"worker.min.js",corePath:root+"core",langPath:root,workerBlobURL:false,gzip:true,logger:m=>{const p=Math.round((Number(m.progress)||0)*100);bar.style.width=p+"%";label.textContent=`正在识别… ${p}%`}});const result=await worker.recognize(canvas),text=(result?.data?.text||"").trim();await worker.terminate();worker=null;$(target).value=text;bar.style.width="100%";label.textContent=text?"识别完成，请核对文字":"未识别到文字，请换更清晰的图片";const d=state(),kind=target==="#jdRaw"?"jd":"resume";if(kind==="jd"){d.jd=d.jd||{};d.jd.raw=text}else d.resumeRaw=text;d.ocrDocuments.unshift({id:crypto.randomUUID(),name:file.name||"手机截图",text,kind,createdAt:new Date().toISOString(),status:"pending"});await save(d);globalThis.DeskStore.toast(text?"OCR 已填入业务表单":"没有识别到文字")}catch(e){if(worker){try{await worker.terminate()}catch{}worker=null}label.textContent="识别失败，可直接粘贴文字";console.error(e);globalThis.DeskStore.toast("OCR 识别失败，请换清晰图片")}}
  function lines(text){return text.split(/\n+/).map(x=>x.trim()).filter(x=>x.length>4)}
  async function analyzeJd(){
    const raw=$("#jdRaw").value.trim();
    if(!raw)return globalThis.DeskStore.toast("请先上传或粘贴 JD");
    if(aiConfig().key){if(!confirm(`将把当前 JD 与已确认的职业记忆发送给 ${aiPresets[aiConfig().provider]?.label||aiConfig().provider} 分析，是否继续？`))return;try{globalThis.DeskStore.toast("Buddy 正在分析 JD…");const d=state(),verified=d.agentMemory.filter(m=>m.verified).map(m=>m.content).join("\n"),answer=await aiRequest([{role:"system",content:'你是求职面试分析助手。只依据用户提供的 JD 和已确认经历，输出严格 JSON：{"duties":"核心职责，每行一条","requirements":"关键要求，每行一条","matches":"匹配经历与依据，每行一条","risks":"风险与补救，每行一条"}。不得捏造经历或数据。'},{role:"user",content:`<JD>\n${raw.slice(0,16000)}\n</JD>\n<已确认经历>\n${verified||"暂无"}\n</已确认经历>`}]),x=parseJsonAnswer(answer);d.jd=Object.assign({},d.jd,{raw,duties:x.duties||"",requirements:x.requirements||"",matches:x.matches||"",risks:x.risks||""});await save(d,"AI 分析已生成，请核对后保存");return}catch(e){return globalThis.DeskStore.toast(e.message||"AI 分析失败")}}
    const d=state(),ls=lines(raw),dutyWords=/负责|推动|搭建|制定|协同|管理|运营|分析|策划|优化/,reqWords=/要求|具备|熟悉|经验|能力|优先|本科|英语|数据|AI/i,verified=d.agentMemory.filter(m=>m.verified).map(m=>m.content),evidence=["新品上市项目","社区增长 0→1","内容增长项目","AI 工作流原型"],terms=[...new Set((raw.match(/[A-Za-z][A-Za-z+.#-]{1,}|[一-龥]{2,6}/g)||[]).filter(x=>/AI|产品|增长|市场|运营|数据|GTM|内容|用户|英语|海外/i.test(x)))];
    const duties=ls.filter(x=>dutyWords.test(x)).slice(0,8).join("\n")||ls.slice(0,5).join("\n");
    const requirements=ls.filter(x=>reqWords.test(x)).slice(0,8).join("\n")||`重点关键词：${terms.slice(0,10).join("、")}`;
    const matches=evidence.map((x,i)=>`${i+1}. ${x}`).join("\n")+(verified.length?`\n\n已确认约束：\n${verified.slice(0,4).map(x=>"- "+x).join("\n")}`:"");
    const risks=["需要用具体项目证据逐条验证岗位关键词，而不是只做同义词匹配。","技术深度、结果归因与数据口径仍需面试前人工确认。","当前为本地规则分析；接入在线 AI 后再生成更细的匹配评分。"].join("\n");
    d.jd=Object.assign({},d.jd,{raw,duties,requirements,matches,risks});
    await globalThis.DeskStore.save(d);
    globalThis.DeskStore.toast("已结合简历证据与已确认记忆生成初步分析");
  }
  async function analyzeResume(){const raw=$("#resumeRaw").value.trim();if(!raw)return globalThis.DeskStore.toast("请先上传简历截图或粘贴简历正文");const d=state();let candidates;if(aiConfig().key){if(!confirm(`简历可能包含个人信息。将把当前简历正文发送给 ${aiPresets[aiConfig().provider]?.label||aiConfig().provider} 提取事实，是否继续？`))return;try{globalThis.DeskStore.toast("Buddy 正在整理简历事实…");const answer=await aiRequest([{role:"system",content:'从简历中提取可核验事实。只输出严格 JSON：{"facts":["事实1","事实2"]}。每条保留主体、动作、时间和数字，不推断，不润色。'},{role:"user",content:raw.slice(0,18000)}]);candidates=(parseJsonAnswer(answer).facts||[]).map(String).slice(0,20)}catch(e){return globalThis.DeskStore.toast(e.message||"AI 整理失败")}}else candidates=lines(raw).filter(x=>/\d|负责|参与|主导|推动|搭建|优化|增长|上线|分析/.test(x)).slice(0,12);const existing=new Set(d.agentMemory.map(m=>m.content));let added=0;for(const x of candidates){if(x.trim()&&!existing.has(x)){d.agentMemory.push(memory(x.trim(),"resume_fact",aiConfig().key?"简历 / AI 整理":"简历 OCR / Agent 整理",false));added++}}await save(d,added?`已整理 ${added} 条待确认简历事实`:"没有发现新的简历事实")}
  async function openPhone(){if(location.protocol==="chrome-extension:"){globalThis.DeskStore.toast("手机接力当前仅在免安装预览版可用");return}try{const info=await fetch("/api/pair-info").then(r=>r.json());if(!globalThis.QRCode)throw Error("二维码组件未加载");$("#phoneUrl").textContent=info.upload_url;$("#phoneQr").innerHTML="";new QRCode($("#phoneQr"),{text:info.upload_url,width:180,height:180,colorDark:"#0f172a",colorLight:"#ffffff",correctLevel:QRCode.CorrectLevel.M});$("#phoneState").textContent="等待手机上传…";$("#phoneDialog").showModal();lastUploadId=info.latest_id||"";clearInterval(pollTimer);pollTimer=setInterval(checkUpload,1500)}catch{globalThis.DeskStore.toast("请用 START_PREVIEW.command 启动，才能使用手机接力")}}
  async function checkUpload(){try{const x=await fetch("/api/latest-upload",{cache:"no-store"}).then(r=>r.json());if(!x.id||x.id===lastUploadId)return;lastUploadId=x.id;$("#phoneState").textContent="已收到图片，正在 OCR…";clearInterval(pollTimer);const blob=await fetch(x.file_url).then(r=>r.blob()),file=new File([blob],x.name||"mobile-upload.jpg",{type:blob.type||"image/jpeg"});$("#phoneDialog").close();await recognize(file,"#jdRaw","#jdOcrProgress")}catch{}}
  async function copyContext(){try{await navigator.clipboard.writeText($("#agentContext").textContent);globalThis.DeskStore.toast("策略上下文已复制")}catch{globalThis.DeskStore.toast("复制失败，请手动选择文本")}}
  function bind(){$("#saveProfile").onclick=saveProfile;$("#addMemory").onclick=addMemory;$("#copyAgentContext").onclick=copyContext;$("#memoryLedger").onclick=e=>{const a=e.target.closest("[data-confirm-memory]"),b=e.target.closest("[data-delete-memory]");if(a)confirmMemory(a.dataset.confirmMemory);if(b)deleteMemory(b.dataset.deleteMemory)};$("#pickJdOcr").onclick=()=>$("#jdOcrFile").click();$("#jdOcrFile").onchange=e=>e.target.files[0]&&recognize(e.target.files[0],"#jdRaw","#jdOcrProgress");$("#pickResumeOcr").onclick=()=>$("#resumeOcrFile").click();$("#resumeOcrFile").onchange=e=>e.target.files[0]&&recognize(e.target.files[0],"#resumeRaw","#resumeOcrProgress");$("#analyzeJd").onclick=analyzeJd;$("#analyzeResume").onclick=analyzeResume;$("#phoneUpload").onclick=openPhone;$("#copyPhoneUrl").onclick=async()=>{await navigator.clipboard.writeText($("#phoneUrl").textContent);globalThis.DeskStore.toast("手机上传地址已复制")};$("#phoneDialog").addEventListener("close",()=>clearInterval(pollTimer));$$('[data-resume-version]').forEach(b=>b.onclick=()=>globalThis.DeskStore.toast(`已选择「${b.dataset.resumeVersion}」作为本次岗位匹配视角`))}
  globalThis.DeskStore.ready.then(async()=>{const d=state(),changed=seedMemory(d);aiSession=await sessionGet();mountAiSettings();loadProfile();bind();globalThis.DeskIntelligence={render,loadProfile,renderAiSettings};if(changed)await globalThis.DeskStore.save(d);render();renderAiSettings()});
})();
