"use strict";
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)], KEY="jobbuddy.interviewDesk.v1";
const seed={jobs:[],jd:{},recaps:[],stars:0,mode:false,activeJobId:null};
const projects=[
 ["新品上市项目",["用户分层","信息架构","跨团队协作","阶段复盘"],"先讲取舍标准，再讲核心链路、执行动作与阶段复盘。"],
 ["社区增长 0→1",["目标用户","小样本验证","内容机制","反馈闭环"],"用用户匹配、反馈和内容沉淀解释渠道价值。"],
 ["内容增长项目",["真实场景","痛点解决","内容组合","漏斗"],"说明内容策略如何从用户问题出发并持续优化。"],
 ["AI 工作流原型",["业务痛点","PRD / MVP","模型调用","人工复核"],"用真实调用和验证结果证明不是静态 Demo。"]
];
const questions=[
 ["项目最困难的地方？",["约束变化","优先级","资源取舍","核心链路"],"难点不是赶工，而是在不确定中做资源取舍。"],
 ["为什么转向产品？",["不是逃离市场","问题抽象","完整闭环","已开始行动"],"从业务痛点走向需求、规则、原型和验证。"],
 ["为什么选择这个渠道？",["用户匹配","直接反馈","内容沉淀","小样本验证"],"回答渠道与目标用户、验证成本和长期价值的关系。"],
 ["如何定义 MVP？",["最高频痛点","最短验证链","成功指标","暂不做"],"用 Copy QA 的准确性、品牌表达和人工通过率回答。"],
 ["哪些结果由你负责？",["直接负责","推动","参与","团队结果"],"主动划清个人动作与项目结果。"],
 ["AI 产品如何做人机分工？",["模型规模化","规则边界","人工审批","反馈闭环"],"人负责高风险判断、品牌责任与例外。"]
];
let data,tab="brief",timerTotal=45,timerLeft=45,timerId=null;
async function read(){let next;if(globalThis.chrome&&chrome.storage&&chrome.storage.local){const r=await chrome.storage.local.get(KEY);next=Object.assign(structuredClone(seed),r[KEY]||{})}else{const raw=localStorage.getItem(KEY);next=raw?Object.assign(structuredClone(seed),JSON.parse(raw)):structuredClone(seed)}next.jobs=(next.jobs||[]).map(j=>Object.assign({},j,{readiness:j.readiness||(+j.progress>=100?"已准备":+j.progress>0?"准备中":"未开始"),updatedAt:j.updatedAt||j.date||j.createdAt||new Date().toISOString()}));return next}
async function write(){if(globalThis.chrome&&chrome.storage&&chrome.storage.local)await chrome.storage.local.set({[KEY]:data});else localStorage.setItem(KEY,JSON.stringify(data))}
function esc(s=""){return String(s).replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]))}
function toast(s){$("#toast").textContent=s;$("#toast").classList.add("show");setTimeout(()=>$("#toast").classList.remove("show"),1800)}
function tags(xs){return '<div class="tags">'+xs.map(x=>'<span class="tag">'+esc(x)+"</span>").join("")+"</div>"}
function activeJob(){return data.jobs.find(x=>x.id===data.activeJobId)||data.jobs[0]}
function renderJobs(){const j=activeJob();$("#jobSelect").innerHTML=data.jobs.length?data.jobs.map(x=>'<option value="'+x.id+'" '+(j&&x.id===j.id?"selected":"")+'>'+esc(x.company)+" · "+esc(x.role)+"</option>").join(""):'<option>尚未添加岗位</option>';$("#jobSelect").disabled=!data.jobs.length;$("#jobMeta").textContent=j?j.stage+" · "+(j.readiness||"未开始"):"点击下方按钮，从招聘页读取岗位"}
function cue(title,keys,answer){return '<article class="cue"><h3>'+esc(title)+"</h3>"+tags(keys)+'<button class="reveal">查看思路</button><p class="answer">'+esc(answer)+"</p></article>"}
function storyCue(s){return cue(s.id+" · "+s.title,[...(s.tags||[]).slice(0,3),"对外 "+(s.grade||"待确认")],s.answer||s.support||s.oneLiner)}
function render(){const names=[["brief","岗位"],["intro","介绍"],["stories","故事"],["projects","项目"],["questions","问题"],["timer","计时"]];$("#tabs").innerHTML=names.map(x=>'<button data-tab="'+x[0]+'" class="'+(tab===x[0]?"active":"")+'">'+x[1]+"</button>").join("");$$("[data-tab]").forEach(b=>b.onclick=()=>{tab=b.dataset.tab;render()});const j=activeJob();if(tab==="brief"){$("#content").innerHTML=j?'<article class="brief"><span class="pill blue">'+esc(j.stage)+'</span><h2>'+esc(j.company)+" · "+esc(j.role)+"</h2>"+tags(["匹配经历","最大风险","反问问题"])+'<p>进入完整看板完成 JD 拆解；面试前把这三个标签各压缩成一句话。</p></article>':'<div class="empty">先添加一个目标岗位</div>'}else if(tab==="intro"){$("#content").innerHTML=cue("30 秒自我介绍",["当前身份","核心方向","代表项目","岗位连接"],"身份 → 核心能力 → 项目证据 → 岗位连接。")}else if(tab==="stories"){const stories=globalThis.StoryLibrary?.stories||[];$("#content").innerHTML=stories.length?stories.map(storyCue).join(""):'<div class="empty">正在读取故事库…</div>'}else if(tab==="projects"){$("#content").innerHTML=projects.map(x=>cue(x[0],x[1],x[2])).join("")}else if(tab==="questions"){$("#content").innerHTML=questions.map(x=>cue(x[0],x[1],x[2])).join("")}else renderTimer();$$(".reveal").forEach(b=>b.onclick=()=>b.closest(".cue").classList.toggle("open"))}
function renderTimer(){const modes=[["一句话",15],["45 秒",45],["90 秒",90],["3 分钟",180]];$("#content").innerHTML='<div class="timer"><div class="timer-modes">'+modes.map(x=>'<button data-seconds="'+x[1]+'" class="'+(x[1]===timerTotal?"active":"")+'">'+x[0]+'</button>').join("")+'</div><div id="clock">'+format(timerLeft)+'</div><button id="timerStart" class="primary">开始</button> <button id="timerReset" class="secondary">重置</button></div><article class="brief"><h2>本轮提示</h2>'+tags(["结论先行","一个判断","两个动作","结果与归因"])+"</article>";$$("[data-seconds]").forEach(b=>b.onclick=()=>{clearInterval(timerId);timerId=null;timerTotal=timerLeft=+b.dataset.seconds;renderTimer()});$("#timerStart").onclick=startTimer;$("#timerReset").onclick=()=>{clearInterval(timerId);timerId=null;timerLeft=timerTotal;renderTimer()}}
function format(s){return String(Math.floor(s/60)).padStart(2,"0")+":"+String(s%60).padStart(2,"0")}
function startTimer(){if(timerId){clearInterval(timerId);timerId=null;$("#timerStart").textContent="继续";return}$("#timerStart").textContent="暂停";timerId=setInterval(async()=>{timerLeft--;$("#clock").textContent=format(timerLeft);if(timerLeft<=0){clearInterval(timerId);timerId=null;data.stars=(data.stars||0)+1;await write();$("#timerStart").textContent="再来一次";toast("练习完成")}},1000)}
function extractPageJob(){
 function findJob(v){if(!v)return null;if(Array.isArray(v)){for(const x of v){const f=findJob(x);if(f)return f}}else if(typeof v==="object"){const t=v["@type"];if(t==="JobPosting"||(Array.isArray(t)&&t.includes("JobPosting")))return v;for(const x of Object.values(v)){const f=findJob(x);if(f)return f}}return null}
 const clean=v=>String(v||"").replace(/<script[\s\S]*?<\/script>/gi," ").replace(/<style[\s\S]*?<\/style>/gi," ").replace(/<[^>]+>/g," ").replace(/\s+/g," ").trim();
 const firstText=selectors=>{for(const selector of selectors){const el=document.querySelector(selector),value=el?.content||el?.innerText||el?.textContent;if(clean(value))return clean(value)}return ""};
 let job=null;for(const s of document.querySelectorAll('script[type="application/ld+json"]')){try{job=findJob(JSON.parse(s.textContent));if(job)break}catch{}}
 let locationText="";if(job?.jobLocation){const l=Array.isArray(job.jobLocation)?job.jobLocation[0]:job.jobLocation,a=l?.address||{};locationText=[a.addressLocality,a.addressRegion,a.addressCountry].filter(Boolean).join(" ")}
 const candidates=[...document.querySelectorAll('[data-automation*="jobDescription" i],[data-testid*="job-description" i],[class*="job-description" i],[id*="job-description" i],[class*="jobDescription" i],[id*="jobDescription" i],[class*="job-detail" i],[class*="description" i],main,article')].map(el=>clean(el.innerText||el.textContent)).filter(text=>text.length>=120).sort((a,b)=>b.length-a.length);
 const fallback=candidates.find(text=>/(岗位职责|职位描述|任职要求|工作内容|responsibilities|qualifications|job description)/i.test(text))||candidates[0]||"";
 const description=clean(job?.description)||fallback;
 const company=clean(job?.hiringOrganization?.name)||firstText(['[data-company-name]','[class*="company-name" i]','[class*="companyName" i]','meta[property="og:site_name"]']);
 const role=clean(job?.title)||firstText(['[data-job-title]','[class*="job-title" i]','[class*="jobTitle" i]','h1','meta[property="og:title"]'])||document.title.split(/[-_|]/)[0];
 const locationValue=locationText||firstText(['[data-job-location]','[class*="job-location" i]','[class*="location" i]']);
 const keywordHits=(description.match(/岗位职责|职位描述|任职要求|工作内容|岗位要求|responsibilities|qualifications|requirements|job description/gi)||[]).length;
 return {company,role,location:locationValue,description:description.slice(0,12000),url:location.href,confidence:job?"structured":keywordHits>=2?"content":"low"};
}
async function capture(targetTabId){try{const [activeTab]=await chrome.tabs.query({active:true,currentWindow:true}),tabInfo=targetTabId?{id:targetTabId,url:activeTab?.id===targetTabId?activeTab.url:"https://pending.local"}:activeTab;if(!tabInfo||!/^https?:/.test(tabInfo.url||""))throw Error("请在招聘网页上使用");const [r]=await chrome.scripting.executeScript({target:{tabId:tabInfo.id},func:extractPageJob});const x=r.result||{};$("#cCompany").value=x.company;$("#cRole").value=x.role;$("#cLocation").value=x.location;$("#cDescription").value=x.description;$("#captureDialog").dataset.url=x.url;$("#captureDialog").showModal();toast(x.confidence==="low"?"已读取网页正文，请重点核对":"已识别岗位信息，请核对")}catch(e){toast(e.message||"无法读取这个页面")}}
async function saveCapture(){const now=new Date().toISOString(),j={id:crypto.randomUUID(),company:$("#cCompany").value||"待确认公司",role:$("#cRole").value||"待确认岗位",stage:"准备投递",readiness:"未开始",updatedAt:now,location:$("#cLocation").value,url:$("#captureDialog").dataset.url,createdAt:now};data.jobs.unshift(j);data.activeJobId=j.id;if($("#cDescription").value){data.jd={company:j.company,role:j.role,raw:$("#cDescription").value,duties:"",requirements:"",matches:"",risks:""}}await write();$("#captureDialog").close();renderJobs();render();toast("已保存到投递看板")}
function search(){const q=$("#quickSearch").value.trim().toLowerCase();if(!q){render();return}const classic=[...projects,...questions].filter(x=>x.join(" ").toLowerCase().includes(q)).map(x=>cue(x[0],x[1],x[2])),stories=(globalThis.StoryLibrary?.stories||[]).filter(s=>[s.id,s.title,s.category,...s.tags,...s.roles,s.oneLiner,s.answer,s.support,s.boundaries].join(" ").toLowerCase().includes(q)).map(storyCue),all=[...stories,...classic];$("#content").innerHTML=all.length?all.join(""):'<div class="empty">没有找到相关内容</div>';$$(".reveal").forEach(b=>b.onclick=()=>b.closest(".cue").classList.toggle("open"))}
async function init(){data=await read();renderJobs();render();$("#openDashboard").onclick=()=>{if(globalThis.chrome&&chrome.runtime&&chrome.runtime.sendMessage)chrome.runtime.sendMessage({type:"open-dashboard"});else location.href="dashboard.html"};$("#captureBtn").onclick=globalThis.chrome&&chrome.scripting?()=>capture():()=>toast("安装扩展后可读取招聘页");$("#saveCapture").onclick=saveCapture;$$("[data-close]").forEach(b=>b.onclick=()=>b.closest("dialog").close());$("#jobSelect").onchange=async e=>{data.activeJobId=e.target.value;await write();renderJobs();render()};$("#quickSearch").oninput=search;if(globalThis.chrome&&chrome.storage&&chrome.storage.onChanged)chrome.storage.onChanged.addListener(async()=>{data=await read();renderJobs()});if(globalThis.chrome?.storage?.session){const {pendingJobCapture}=await chrome.storage.session.get("pendingJobCapture");if(pendingJobCapture&&Date.now()-pendingJobCapture.at<15000){await chrome.storage.session.remove("pendingJobCapture");setTimeout(()=>capture(pendingJobCapture.tabId),120)}}}
init();
if(globalThis.StoryLibrary)globalThis.StoryLibrary.ready.then(()=>data&&render());
